name       : ding-libs
version    : 0.4.0
release    : 2
source     :
    - https://github.com/SSSD/ding-libs/archive/ding_libs-0_4_0.tar.gz : becbe39cd25b5aec508c345747fbade276668b4707f2fadd0f9f97ec75459767
license    : GPL-3.0
component  : programming
summary    : DING helper libraries for SSSD and FreeIPA
description: |
    DING helper libraries for SSSD and FreeIPA
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
